* Joestar
Joestar is a minor mode for emacs that seeks to emulate [[https://github.com/jhallen/joe-editor][Joe's Own Editor]], a wordstar-like terminal text editor. 
* Known Issues
The keyboard shortcut to insert a shell command currently does not work properly. 
In order to insert shell output call the joe-insertcmd function directly.
* TODO Goals for Next Major Version
- [ ] Find function
- [ ] Regions
- [ ] Keyboard Macros

* Basic Tutorial
** A note on Control key sequences
Because of the way that Joe works *C-k C-e* is the same as *C-k e*. 
However, Emacs considers these to be different key sequences. 
In joestar mode, just like in joe, these are the same sequence.
** Help
Type *C-k h* for help.
** Region
- *C-<arrow>*
Control selection.
- *C-k c*
Copy region.
- *C-k w*
Write to file.
- *C-k y*
Delete region
** Goto
- *C-z*
Back one word.
- *C-x*
Forward one word.
- *C-k C-u*
Top of file.
- *C-k C-v*
End of file.
- *C-a*
Beginning of line (first non-indentation character).
- *C-e*
End of line.
- *C-k l*
To line number.
- *C-u*
Up one screen.
- *C-v*
Down one screen.
