#+TITLE: Joestar
#+AUTHOR: Ryan Jeffrey
#+EMAIL: pwishie@gmail.com
#+OPTIONS: num:nil

Joestar is a minor mode for emacs that seeks to emulate [[https://github.com/jhallen/joe-editor][Joe's Own Editor]], a wordstar-like terminal text editor.
* Installation
Joestar needs the libraries [[https://www.emacswiki.org/emacs/HighlightLibrary][Highlight]] and [[https://github.com/apchamberlain/undo-tree.el][Undo Tree]]. Once you have those:
#+BEGIN_SRC shell
  cd ~/.emcas.d/
  git clone https://github.com/Ma11ock/joestar
#+END_SRC

Then, in your emacs configuration file:

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/joestar/")
  (require 'joestar)
  ;; you can hook joestar to prog-mode like:
  (add-hook 'prog-mode-hook 'joestar-mode)

#+END_SRC
* Configuration
** Undo-tree
Joestar uses undo-tree to get a more accurate undoing experience to Joe.
However, a few of undo-tree's default keybindings conflict with Joestar's.
To fix this problem add this to your config /(before Joestar is loaded)/.
#+BEGIN_SRC emacs-lisp

(defvar undo-tree-map
          (let ((map (make-sparse-keymap)))
              ;; remap `undo' and `undo-only' to `undo-tree-undo'
              (define-key map [remap undo] 'undo-tree-undo)
              (define-key map [remap undo-only] 'undo-tree-undo)
              ;; bind standard undo bindings (since these match redo counterparts)
              (define-key map (kbd "C-/") 'undo-tree-undo)
              (define-key map "\C-_" 'undo-tree-undo)
              ;; redo doesn't exist normally, so define our own keybindings
              (define-key map (kbd "C-?") 'undo-tree-redo)
              (define-key map (kbd "M-_") 'undo-tree-redo)
              ;; just in case something has defined `redo'...
              (define-key map [remap redo] 'undo-tree-redo)
              ;; we use "C-x u" for the undo-tree visualizer
              (define-key map (kbd "s-x u") 'undo-tree-visualize)
              ;; bind register commands
              (define-key map (kbd "s-x r u") 'undo-tree-save-state-to-register)
              (define-key map (kbd "s-x r U") 'undo-tree-restore-state-from-register)
              ;; set keymap
          (setq undo-tree-map map)))

(require 'joestar)

#+END_SRC

If you are using use-package this would be done with *:init*.
* Known Issues
The find feature is supposed to store the last task of the user and set it to the default next time find is called.
This works the first time a find command is repeated, but not subsequent times.

* TODO Goals for Beta Version [1/5]
- [X] Find function
- [ ] Keyboard Macro
- [ ] Cancel features
- [ ] Help buffer
- [ ] Full Block implementation
