* Joestar
Joestar is a minor mode for emacs that seeks to emulate [[https://github.com/jhallen/joe-editor][Joe's Own Editor]], a wordstar-like terminal text editor. 
* Known Issues
The keyboard shortcut to insert a shell command currently does not work properly. 
In order to insert shell output call the joe-insertcmd function directly.
* Joestar and undo-tree
Joestar depends on undo-tree, which uses C-x for several of its keybindings, which conflicts with Joestar's usage of C-x.
In order to fix this, Joestar remaps the three following functions:
#+BEGIN_SRC emacs-lisp

(define-key map (kbd "s-x u") 'undo-tree-visualize)
(define-key map (kbd "s-x r u") 'undo-tree-save-state-to-register)
(define-key map (kbd "s-x r U") 'undo-tree-restore-state-from-register)

#+END_SRC 
* Tutorial
** A note on Control key sequences
Because of the way that Joe works *C-k C-e* is the same as *C-k e*. 
However, Emacs considers these to be different key sequences. 
In joestar mode, just like in joe, these are the same sequence.
** Help
Type *C-k h* for help.
** Region
- *C-<arrow>*
Control selection.
- *C-k c*
Copy region.
- *C-k w*
Write to file.
- *C-k y*
Delete region
** Goto
- *C-z*
Back one word.
- *C-x*
Forward one word.
- *C-k C-u*
Top of file.
- *C-k C-v*
End of file.
- *C-a*
Beginning of line (first non-indentation character).
- *C-e*
End of line.
- *C-k l*
To line number.
- *C-u*
Up one screen.
- *C-v*
Down one screen.

