* Joestar
Joestar is a minor mode for emacs that seeks to emulate [[https://github.com/jhallen/joe-editor][Joe's Own Editor]], a wordstar-like terminal text editor. 
* Configuration
** Undo-tree
Joestar uses undo-tree to get a more accurate undoing experience to Joe.
However, a few of undo-tree's default keybindings conflict with Joestar's.
To fix this problem add this to your config /(before Joestar is loaded)/.
#+BEGIN_SRC emacs-lisp

(defvar undo-tree-map
          (let ((map (make-sparse-keymap)))
              ;; remap `undo' and `undo-only' to `undo-tree-undo'
              (define-key map [remap undo] 'undo-tree-undo)
              (define-key map [remap undo-only] 'undo-tree-undo)
              ;; bind standard undo bindings (since these match redo counterparts)
              (define-key map (kbd "C-/") 'undo-tree-undo)
              (define-key map "\C-_" 'undo-tree-undo)
              ;; redo doesn't exist normally, so define our own keybindings
              (define-key map (kbd "C-?") 'undo-tree-redo)
              (define-key map (kbd "M-_") 'undo-tree-redo)
              ;; just in case something has defined `redo'...
              (define-key map [remap redo] 'undo-tree-redo)
              ;; we use "C-x u" for the undo-tree visualizer
              (define-key map (kbd "s-x u") 'undo-tree-visualize)
              ;; bind register commands
              (define-key map (kbd "s-x r u") 'undo-tree-save-state-to-register)
              (define-key map (kbd "s-x r U") 'undo-tree-restore-state-from-register)
              ;; set keymap
          (setq undo-tree-map map)))

(require 'joestar)

#+END_SRC

If you are using use-package this would be done with *:init*.
* Known Issues
The keyboard shortcut to insert a shell command currently does not work properly. 
In order to insert shell output call the joe-run function directly.

* Basic Tutorial
For a more detailed tutorial, see tutorial.org; or *C-k C-h* in Emacs for help.
** A note on Control key sequences
Because of the way that Joe works *C-k C-e* is the same as *C-k e*. 
However, Emacs considers these to be different key sequences. 
In joestar mode, just like in joe, these are the same sequence.
** Keybindings
Type *C-k h* for help.
- *C-<arrow>*
Control selection.
- *C-k c*
Copy region.
- *C-k w*
Write to file.
- *C-k y*
Delete region
- *C-z*
Back one word.
- *C-x*
Forward one word.
- *C-k C-u*
Top of file.
- *C-k C-v*
End of file.
- *C-a*
Beginning of line (first non-indentation character).
- *C-e*
End of line.
- *C-k l*
To line number.
- *C-u*
Up one screen.
- *C-v*
Down one screen.
- *C-k C-d*
Saving
- *C-k C-f*
Joe's find function.
* TODO Goals for Next Major Version
- [X] Find function
- [ ] Regions
- [ ] Keyboard Macros
